apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-twin-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 97k.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: digital-twin-api
            port:
              number: 80
                - host: 97v.ru
                    http:
                          paths:
                                  - path: /
                                            pathType: Prefix
                                                      backend:
                                                                  service:
                                                                                name: digital-twin-api
                                                                                              port:
                                                                                                              number: 80
