apiVersion: v1
kind: Service
metadata:
  name: digital-twin-api
  labels:
    app: digital-twin-api
spec:
  type: ClusterIP
  selector:
    app: digital-twin-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
